### ISSUE TITLE
有参创建方式创建weid与文档说明不符

### ISSUE THREAD

**Issue by ouerum** [WeBankFinTech/WeIdentity-Rest-Service#24]
轻客户端中调用有参创建方式创建weid的接口，即使创建weid成功，接口也没有返回weid的值。
按照文档说明，返回的json串应该是
`{
    "ErrorCode": 0,
    "ErrorMessage": "success",
    "respBody": "did:weid:0xfd28ad212a2de77fee518b4914b8579a40c601fa"
}`
实际上返回
`{
    "ErrorCode": 0,
    "ErrorMessage": "success",
    "respBody": null
}`
主要的问题出现在weid-java-sdk中，具体是rawTransactionService.createWeId()在注册weid后，并没有把weid打包返回，只返回bool值。并在TransactionServiceImpl的256行把bool值转成null。
可以通过rest service里面Transaction TestV2的testCreateWeIdAll()测试用例复现。

**Comment by chaoxinhu** [comment]
此问题后续排版修复，谢谢！
