### ISSUE TITLE
createCredential后verifyCreential不成功

### ISSUE THREAD

**Issue by leeduckgo** [WeBankFinTech/WeIdentity-Rest-Service#51]
但是verifyCredentailPojo是成功的。

**Comment by leeduckgo** [comment]
credential原文：
```
{
        "issuer": "did:weid:1:0x3462a28112da8f419b13e2f44412483304a835f3",
        "cptId": "1001",
        "expirationDate": "2100-04-18T21:12:33Z",
        "claim": {
        	"test": "sth"
        }
    }
```

**Comment by leeduckgo** [comment]
Response Credential:
```
 {
        "@context": "https://github.com/WeBankFinTech/WeIdentity/blob/master/context/v1",
        "claim": {
            "test": "sth"
        },
        "cptId": 1001,
        "expirationDate": "2100-04-18T21:12:33Z",
        "id": "8cd0d7b2-f3a2-4344-9061-cf72de757106",
        "issuanceDate": "2020-12-31T14:35:20Z",
        "issuer": "did:weid:1:0x3462a28112da8f419b13e2f44412483304a835f3",
        "proof": {
            "created": "1609396520000",
            "creator": "did:weid:1:0x3462a28112da8f419b13e2f44412483304a835f3",
            "signature": "koxGZ0JoNxgMgRq5Kx5B2FKmccoVDssiWOs/lKskrlNNuATfw0ThFbcMVg4g8bZpS8rVuyMdP67jcmZLVbUlywE=",
            "type": "Secp256k1"
        }
    }
```

**Comment by junqizhang-dev** [comment]
使用的 rest service 的commit是：7af306059b5774d2fd80b5124df96aaaeab2030a

可以用这个credential复现。
{
    "respBody": {
        "@context": "https://github.com/WeBankFinTech/WeIdentity/blob/master/context/v1",
        "claim": {
            "test": "sth"
        },
        "cptId": 1001,
        "expirationDate": "2100-04-18T21:12:33Z",
        "id": "8cd0d7b2-f3a2-4344-9061-cf72de757106",
        "issuanceDate": "2020-12-31T14:35:20Z",
        "issuer": "did:weid:1:0x3462a28112da8f419b13e2f44412483304a835f3",
        "proof": {
            "created": "1609396520000",
            "creator": "did:weid:1:0x3462a28112da8f419b13e2f44412483304a835f3",
            "signature": "koxGZ0JoNxgMgRq5Kx5B2FKmccoVDssiWOs/lKskrlNNuATfw0ThFbcMVg4g8bZpS8rVuyMdP67jcmZLVbUlywE=",
            "type": "Secp256k1"
        }
    },
    "loopback": null,
    "errorCode": 0,
    "errorMessage": "success"
}
