### ISSUE TITLE
问一下，你们1.6 或者 支持 FISCO-BCOS 3.x 的版本什么时候发布？

### ISSUE THREAD

**Issue by Degfy** [WeBankFinTech/WeIdentity-Rest-Service#78]

**Comment by Degfy** [comment]
自己来回答吧：
千万不要去拉tag的代码，反正 [v1.5.8](https://github.com/WeBankBlockchain/WeIdentity-Rest-Service/tree/v1.5.8) 的代码有问题，gradle版本有问题，编译不过。

1.6的代码已经发布了，在[release/1.6.0](https://github.com/WeBankBlockchain/WeIdentity-Rest-Service/tree/release/1.6.0)分支上。

**Comment by susengo** [comment]
大佬，有遇到过这个问题吗？我第一步调用创建weID就报错，如下。环境是java1.8、fisco bcos版本是2.8、weid-rest是1.6。
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/19683278/224280673-2a9912d3-e2c1-423e-98fd-ff4aeb022d1b.png">
